backend:
  name: git-gateway
  branch: master

media_folder: content/uploads
public_folder: content/uploads

locale: it

collections:
  - name: 'home-intro'
    label: 'Intro Home'
    create: false
    files:
      - name: 'intro-text'
        label: 'Testo Intro'
        file: 'content/home/intro.md'
        fields:
          - { label: 'Titolo', name: 'title', widget: 'string' }
          - { label: 'Testo', name: 'body', widget: 'markdown' }
          - { label: 'Foto Copiatrice', name: 'featuredImage', widget: 'image', default: 'intro-printer.png' }

  - name: 'home'
    label: 'Servizi'
    folder: 'content/home/services'
    create: true
    # slug: 'index'
    fields:
      - { label: 'Titolo', name: 'title', widget: 'string' }
      - { label: 'Immagine', name: 'featuredImage', widget: 'image', default: 'home-entry-default.jpg' }
      - { label: 'Descrizione', name: 'body', widget: 'markdown' }

  - name: 'promo'
    label: 'Promo'
    folder: 'content/promo'
    create: true
    # slug: 'index'
    fields:
      - { label: 'Titolo', name: 'title', widget: 'string' }
      - { label: 'Prezzo', name: 'price', widget: 'string' }
      - { label: 'Immagine', name: 'featuredImage', widget: 'image', default: 'home-entry-default.jpg' }
      - { label: 'Descrizione', name: 'body', widget: 'markdown' }

  - name: 'info'
    label: 'Info'
    create: false
    editor:
      preview: false
    files:
      - label: 'Business Info'
        name: 'business-info'
        file: 'content/business-info.md'
        fields:
          - { label: 'e-mail', name: 'email', widget: 'string' }
          - { label: 'Telefono', name: 'phone', widget: 'string' }
          - { label: 'Indirizzo', name: 'address', widget: 'string' }
          - { label: 'Link a Indirizzo', name: 'addressLink', widget: 'string' }
          - { label: 'Chi Siamo', name: 'body', widget: 'markdown' }
